export const FORMAT_DATE = "DD/MM/YYYY";
export const UNLIMITED = 9999999999
export const ATTACH_FILE_PDF = 'application/pdf';
export const ATTACH_FILE_DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
export const ATTACH_FILE_PPT = 'application/vnd.ms-powerpoint';
export const ATTACH_FILE_PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
export const ATTACH_FILE_XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
export const VIDEO_FILE_MP4 = 'video/mp4';
export const VIDEO_FILE_WMV = 'video/x-ms-wmv';
export const IMAGE_FILE_PNG = 'image/png';
export const IMAGE_FILE_JPEG = 'image/jpeg';
export const IMAGE_FILE_JPG = 'image/jpg';
export const LIST_IMAGE_FILE_TYPE = [IMAGE_FILE_PNG, IMAGE_FILE_JPEG, IMAGE_FILE_JPG];
export const LIST_VIDEO_FILE_TYPE = [VIDEO_FILE_MP4, VIDEO_FILE_WMV];
export const LIST_ATTACH_FILE_TYPE = [ATTACH_FILE_DOCX, ATTACH_FILE_PDF, ATTACH_FILE_PPT, ATTACH_FILE_PPTX, ATTACH_FILE_XLSX];
export const REMIND_USER = 'REMIND_USER';
export const TYPE_VIDEO_ORIGIN = ['mp4', 'wmv'];